# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

# you can choose themes from $HOME/.config/kitty/kitty-themes/
include ./kitty-themes/00-Default.conf

font_family FantasqueSansM Nerd Font Mono Bold
font_size 16.0
bold_font auto
italic_font auto
bold_italic_font auto

background_opacity 0.9
dynamic_background_opacity 1
confirm_os_window_close 0

# Animated cursor
cursor_trail 1

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4

selection_foreground none
selection_background none

foreground #ffffff
background #000000
cursor #ffffff

# ANSI colors
color0  #000000  # preto
color1  #cc0000  # vermelho
color2  #4e9a06  # verde
color3  #222222  # amarelo (segmento git)
color4  #000000  # azul (segmento de data/hora — mais escuro)
color5  #ffffff  # magenta (texto do segmento usuário@host)
color6  #111111  # ciano (segmento diretório)
color7  #ffffff  # branco
color8  #555753  # cinza (preto brilhante)
color9  #ef2929  # vermelho brilhante
color10 #8ae234  # verde brilhante
color11 #fce94f  # amarelo brilhante
color12 #729fcf  # azul brilhante
color13 #ad7fa8  # magenta brilhante
color14 #34e2e2  # ciano brilhante
color15 #ffffff  # branco brilhante
